version: 2.1
jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: make
  test:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run: make test

workflows:
  version: 2.1
  test:
    jobs:
      - build
      - test